import {
  AlertTriangle,
  BookOpen,
  Bug,
  CheckCircle2,
  Compass,
  FileSignature,
  FileText,
  HeartHandshake,
  Image as ImageIcon,
  KeyRound,
  LayoutDashboard,
  Link2,
  LockKeyhole,
  MessageCircleQuestion,
  Plug,
  RadioTower,
  ShieldAlert,
  Sparkles,
  UserRound,
  UsersRound,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export type LilithSliceType =
  | 'landing'
  | 'workspace'
  | 'generator'
  | 'console'
  | 'auth'
  | 'content'
  | 'document'
  | 'status'
  | 'redirect'
  | 'debug'
  | 'community';

export type LilithSlice = {
  slug: string;
  route: string;
  sourceFile: string;
  title: string;
  shortTitle: string;
  type: LilithSliceType;
  icon: LucideIcon;
  summary: string;
  primaryTask: string;
  desktopStrategy: string;
  mobileStrategy: string;
  modules: string[];
  interactions: string[];
  boundaries: string[];
};

export const sliceTypeLabels: Record<LilithSliceType, string> = {
  landing: '入口页',
  workspace: '工具台',
  generator: '生成器',
  console: '控制台',
  auth: '认证流程',
  content: '内容帮助',
  document: '协议文档',
  status: '状态页',
  redirect: '跳转页',
  debug: '调试页',
  community: '社区页',
};

export const lilithSlices: LilithSlice[] = [
  {
    slug: 'home',
    route: '/',
    sourceFile: 'src/app/page.tsx',
    title: '首页工作台入口',
    shortTitle: '首页',
    type: 'landing',
    icon: Compass,
    summary: '把首页从介绍型页面调整为“开始使用”的入口页，首屏直接给出登录状态、高频工具和最近更新。',
    primaryTask: '让新老用户在 10 秒内找到下一步：登录、进入仪表盘、生成 Best N 或查 FAQ。',
    desktopStrategy: '上方保留品牌与主操作，下方使用 2:1 布局承载高频工具和公告/帮助入口。',
    mobileStrategy: '先展示主 CTA 和工具入口，再展示公告与支持入口，避免长 hero 占满首屏。',
    modules: ['登录/数据状态条', '高频工具入口', '最近更新', 'FAQ 与反馈入口'],
    interactions: ['登录后主按钮变为进入仪表盘', '工具入口支持键盘聚焦', '公告可跳转到详情或收起'],
    boundaries: ['不要做大面积营销 hero', '不要用装饰图填空', '首页不是 Dashboard 的缩略版'],
  },
  {
    slug: 'dashboard',
    route: '/dashboard',
    sourceFile: 'src/app/dashboard/page.tsx',
    title: '仪表盘信息架构切片',
    shortTitle: '仪表盘',
    type: 'workspace',
    icon: LayoutDashboard,
    summary: '仪表盘必须单独设计为高频操作与数据分析界面，不套用普通生成器两栏模板。',
    primaryTask: '让用户在同一屏完成数据状态判断、工具切换、成绩预览和导出/刷新操作。',
    desktopStrategy: '保留强导航能力：左侧工具导航，中间数据工作区，右侧只放当前工具相关状态与风险提示。',
    mobileStrategy: '使用顶部工具 tabs 与分段抽屉，主内容保持单任务流，避免桌面侧栏直接堆到移动端。',
    modules: ['工具导航', '数据同步状态', '成绩摘要', '当前工具面板', '导出与刷新动作'],
    interactions: ['工具切换不丢失当前数据', '刷新失败给恢复路径', '导出前显示数据时间戳'],
    boundaries: ['不能照搬 /dev/lilith 的生成器两栏模板', '不能降低现有数据密度', '不能删除关键筛选和历史入口'],
  },
  {
    slug: 'login',
    route: '/login',
    sourceFile: 'src/app/login/page.tsx',
    title: '登录流程切片',
    shortTitle: '登录',
    type: 'auth',
    icon: UserRound,
    summary: '把登录页设计成稳定流程页，左侧处理登录方式，右侧解释安全、失败原因和协议。',
    primaryTask: '用户清楚选择登录方式，并知道等待、失败、过期时下一步做什么。',
    desktopStrategy: '表单/二维码为主列，右栏为安全说明、常见失败原因和协议入口。',
    mobileStrategy: '登录方式放在顶部 segmented control，说明内容折叠到表单下方。',
    modules: ['登录方式切换', '二维码/Token 表单', '等待确认状态', '失败恢复提示', '协议入口'],
    interactions: ['二维码区域尺寸稳定', '过期可一键刷新', '敏感输入提供显示/隐藏与清除'],
    boundaries: ['不要把帮助说明做成营销文案', '不要让二维码和提示互相挤压', '不要隐藏协议入口'],
  },
  {
    slug: 'open-platform',
    route: '/open-platform',
    sourceFile: 'src/app/open-platform/page.tsx',
    title: '开放平台控制台切片',
    shortTitle: '开放平台',
    type: 'console',
    icon: KeyRound,
    summary: '开发者页应像控制台：表格清晰、危险操作严肃、右侧保留安全和文档上下文。',
    primaryTask: '开发者能创建、轮换、撤销 API Key，并理解每个操作的风险。',
    desktopStrategy: '主区为 API Key 表格与创建表单，右栏显示账户状态、安全提示和文档入口。',
    mobileStrategy: '表格转卡片，危险操作进入站内确认弹窗，文档入口移到折叠资源区。',
    modules: ['开发者状态', 'API Key 列表', '创建/轮换表单', '危险确认', '文档与协议'],
    interactions: ['复制 token 后给一次性提示', '撤销必须二次确认', '表格行操作有图标与文字'],
    boundaries: ['不使用 window.confirm/prompt', '不把密钥值长期展示', '不照搬普通生成器布局'],
  },
  {
    slug: 'unified-api-dashboard',
    route: '/unified-api-dashboard',
    sourceFile: 'src/app/unified-api-dashboard/page.tsx',
    title: '统一 API 工具台切片',
    shortTitle: '统一 API',
    type: 'console',
    icon: Plug,
    summary: '统一 API 面向配置、绑定和接口调试，需要比开放平台更偏工具化，但仍保持清晰分区。',
    primaryTask: '用户能绑定账号、查看凭证、测试接口并理解响应结果。',
    desktopStrategy: '左侧为流程导航，中间为当前配置/测试表单，右侧为响应摘要和文档片段。',
    mobileStrategy: '按“绑定 -> 凭证 -> 测试 -> 响应”顺序堆叠，并保持 JSON 响应可折叠。',
    modules: ['账号绑定', '凭证状态', '接口测试', '响应 JSON', '错误恢复'],
    interactions: ['响应可在摘要/原文间切换', '凭证敏感信息默认隐藏', '失败时显示请求 ID'],
    boundaries: ['不要把所有工具堆在同一长卡片', '不要默认暴露原始响应', '不要弱化错误状态'],
  },
  {
    slug: 'qa',
    route: '/qa',
    sourceFile: 'src/app/qa/page.tsx',
    title: 'FAQ 帮助中心切片',
    shortTitle: 'FAQ',
    type: 'content',
    icon: MessageCircleQuestion,
    summary: 'FAQ 应支持搜索、分类和扫读，而不是静态问题堆叠。',
    primaryTask: '用户能快速定位登录、数据、安全、开放平台相关问题。',
    desktopStrategy: '左侧搜索与分类，右侧问题列表和答案摘要，热门问题在顶部。',
    mobileStrategy: '搜索置顶，分类横向滚动，答案列表保持可折叠。',
    modules: ['搜索框', '分类 tabs', '热门问题', '答案列表', '反馈入口'],
    interactions: ['搜索无结果给反馈入口', '答案可复制锚点', '分类切换不重置搜索词'],
    boundaries: ['空状态提到搜索时必须真的有搜索', '不要把正文拉到全宽', '不要用大卡片堆所有问题'],
  },
  {
    slug: 'about',
    route: '/about',
    sourceFile: 'src/app/about/page.tsx',
    title: '关于页面切片',
    shortTitle: '关于',
    type: 'content',
    icon: BookOpen,
    summary: '关于页保留项目背景，但增加更清晰的站点能力、维护状态和联系入口。',
    primaryTask: '让用户理解项目是什么、能做什么、如何反馈或支持。',
    desktopStrategy: '正文保持可读宽度，侧栏提供项目状态、外链、维护者信息。',
    mobileStrategy: '先展示项目摘要和关键入口，再进入详细说明。',
    modules: ['项目摘要', '能力列表', '维护状态', '联系入口', '相关链接'],
    interactions: ['外链走 /go 安全跳转', '反馈入口明确', '版本/更新时间可见'],
    boundaries: ['不要做营销公司页', '不要把品牌信息只放在顶栏', '不要拉宽长正文'],
  },
  {
    slug: 'sponsors',
    route: '/sponsors',
    sourceFile: 'src/app/sponsors/page.tsx',
    title: '赞助者页面切片',
    shortTitle: '赞助者',
    type: 'community',
    icon: HeartHandshake,
    summary: '赞助页应表达感谢与透明度，同时给出支持方式和项目成本说明。',
    primaryTask: '用户理解赞助用途，并能安全跳转到支持渠道。',
    desktopStrategy: '主区展示赞助名单与说明，右侧放支持入口、透明度和感谢文案。',
    mobileStrategy: '支持入口前置，赞助者列表保持紧凑可扫读。',
    modules: ['赞助入口', '赞助者列表', '费用说明', '感谢说明', '安全外链'],
    interactions: ['外链明确目标域名', '赞助等级可筛选', '空名单也有说明'],
    boundaries: ['不要过度商业化', '不要用夸张 hero', '不要隐藏外链风险'],
  },
  {
    slug: 'contribute',
    route: '/contribute',
    sourceFile: 'src/app/contribute/page.tsx',
    title: '投稿与反馈切片',
    shortTitle: '投稿反馈',
    type: 'content',
    icon: FileSignature,
    summary: '投稿页应把反馈、调查、内容贡献拆成清晰路径，降低表单压力。',
    primaryTask: '用户能选择反馈类型并提交足够上下文。',
    desktopStrategy: '左侧说明贡献路径，右侧为当前表单；提交后给出处理预期。',
    mobileStrategy: '先选择类型，再展示对应字段，避免一屏过长。',
    modules: ['反馈类型', '上下文表单', '提交状态', '处理时效', '外部调查入口'],
    interactions: ['提交失败可重试', '字段说明贴近输入框', '敏感信息提醒'],
    boundaries: ['不要把所有说明放在表单上方', '不要让提交按钮离表单太远', '不要缺少成功状态'],
  },
  {
    slug: 'agreement',
    route: '/agreement',
    sourceFile: 'src/app/agreement/page.tsx',
    title: '用户协议切片',
    shortTitle: '用户协议',
    type: 'document',
    icon: FileText,
    summary: '协议页以阅读舒适和可追溯为核心，宽屏空位用于目录和签名信息。',
    primaryTask: '用户能阅读关键条款、确认更新时间和相关入口。',
    desktopStrategy: '正文 720-820px，右侧目录、更新时间、签名状态和相关链接。',
    mobileStrategy: '目录折叠到正文前，更新时间固定展示。',
    modules: ['正文', '目录', '更新时间', '签名状态', '相关协议入口'],
    interactions: ['目录锚点滚动', '签名状态可查看', '相关协议互链'],
    boundaries: ['不要拉宽正文', '不要把目录做成大卡', '不要用装饰填空'],
  },
  {
    slug: 'privacy',
    route: '/privacy',
    sourceFile: 'src/app/privacy/page.tsx',
    title: '隐私政策切片',
    shortTitle: '隐私政策',
    type: 'document',
    icon: LockKeyhole,
    summary: '隐私页需要比普通协议更突出数据类型、第三方服务和本地存储说明。',
    primaryTask: '用户能快速找到数据收集、存储、第三方服务和删除方式。',
    desktopStrategy: '正文配合右侧目录，顶部增加隐私摘要和数据分类索引。',
    mobileStrategy: '摘要先行，长文目录折叠，关键条款可跳转。',
    modules: ['隐私摘要', '数据分类', '第三方服务', '本地存储说明', '目录'],
    interactions: ['分类索引跳转', '第三方链接走 /go', '更新时间明显'],
    boundaries: ['不要只展示长文', '不要弱化第三方说明', '不要把隐私提示写成广告'],
  },
  {
    slug: 'open-platform-agreement',
    route: '/open-platform/agreement',
    sourceFile: 'src/app/open-platform/agreement/page.tsx',
    title: '开放平台协议切片',
    shortTitle: '开放协议',
    type: 'document',
    icon: ShieldAlert,
    summary: '开放平台协议需要突出 API 使用限制、密钥责任和违规处理。',
    primaryTask: '开发者在申请或使用 API 前理解风险与责任边界。',
    desktopStrategy: '正文 + 开发者责任摘要 + API 风险目录。',
    mobileStrategy: '先展示关键风险摘要，再进入完整协议。',
    modules: ['风险摘要', 'API 使用限制', '密钥责任', '违规处理', '签名状态'],
    interactions: ['风险条款可快速定位', '返回开放平台入口固定可见', '外链安全跳转'],
    boundaries: ['不要做成普通文本页', '不要隐藏风险条款', '不要缺少返回控制台入口'],
  },
  {
    slug: 'banned',
    route: '/banned',
    sourceFile: 'src/app/banned/page.tsx',
    title: '封禁状态页切片',
    shortTitle: '封禁页',
    type: 'status',
    icon: AlertTriangle,
    summary: '封禁页应清楚说明原因、影响范围和申诉路径。',
    primaryTask: '用户知道为什么无法继续、能否恢复、下一步找谁。',
    desktopStrategy: '中心状态说明 + 右侧申诉与安全提醒。',
    mobileStrategy: '状态原因优先，操作按钮紧跟，细节说明折叠。',
    modules: ['状态原因', '影响范围', '申诉入口', '返回首页', '安全说明'],
    interactions: ['复制封禁编号', '申诉入口明确', '返回不丢失原因'],
    boundaries: ['不要只有一句错误', '不要使用恐吓文案', '不要缺少下一步'],
  },
  {
    slug: 'auth',
    route: '/auth',
    sourceFile: 'src/app/auth/page.tsx',
    title: '认证回调页切片',
    shortTitle: '认证回调',
    type: 'status',
    icon: CheckCircle2,
    summary: '认证回调页通常短暂出现，但仍需要稳定 loading、成功和失败状态。',
    primaryTask: '用户知道认证正在处理，失败时能回到登录页或查看原因。',
    desktopStrategy: '单状态卡，展示步骤、错误原因和返回入口。',
    mobileStrategy: '居中状态，不出现额外导航噪音。',
    modules: ['处理中状态', '成功跳转', '失败说明', '返回登录'],
    interactions: ['超时提示', '失败可重试', '保持焦点可达'],
    boundaries: ['不要空白等待', '不要直接闪退无说明', '不要显示敏感参数'],
  },
  {
    slug: 'go',
    route: '/go',
    sourceFile: 'src/app/go/page.tsx',
    title: '外链跳转安全页切片',
    shortTitle: '外链跳转',
    type: 'redirect',
    icon: Link2,
    summary: '外链页应展示目标域名、风险说明和明确继续/取消操作。',
    primaryTask: '用户确认自己将离开本站，并能安全取消。',
    desktopStrategy: '中心确认卡 + 目标 URL 摘要 + 安全提示。',
    mobileStrategy: '目标域名优先展示，长链接折叠。',
    modules: ['目标域名', '安全提示', '继续跳转', '取消返回', '复制链接'],
    interactions: ['倒计时可取消', '目标链接可复制', '危险域名高亮'],
    boundaries: ['不要自动跳转到未知域名', '不要隐藏完整链接', '不要弱化取消按钮'],
  },
  {
    slug: 'unified-api',
    route: '/unified-api',
    sourceFile: 'src/app/unified-api/page.tsx',
    title: '统一 API 重定向页切片',
    shortTitle: '统一 API 跳转',
    type: 'redirect',
    icon: RadioTower,
    summary: '服务端重定向页本身无可视内容，但设计切片应定义降级时的可见状态。',
    primaryTask: '当重定向失败或 JS 不可用时，用户仍能进入正确控制台。',
    desktopStrategy: '轻量状态页，展示目标路由和手动跳转入口。',
    mobileStrategy: '单按钮恢复路径，减少信息量。',
    modules: ['跳转目标', '手动进入', '失败提示', '返回首页'],
    interactions: ['自动跳转失败后显示按钮', '保留 noindex', '记录重定向原因'],
    boundaries: ['不要为重定向页增加复杂 UI', '不要出现空白失败', '不要改变服务端重定向语义'],
  },
  {
    slug: 'debug-auth',
    route: '/debug-auth',
    sourceFile: 'src/app/debug-auth/page.tsx',
    title: '认证调试页切片',
    shortTitle: '认证调试',
    type: 'debug',
    icon: Bug,
    summary: '调试页需要清楚区分测试输入、敏感输出和恢复操作。',
    primaryTask: '开发者能检查认证状态，同时避免误暴露凭证。',
    desktopStrategy: '左侧测试表单，中间状态结果，右侧安全注意事项。',
    mobileStrategy: '输入、结果、说明分段堆叠，敏感结果默认折叠。',
    modules: ['测试输入', '会话状态', '响应详情', '安全提示', '返回入口'],
    interactions: ['敏感字段 reveal 前确认', '复制结果可脱敏', '错误显示请求 ID'],
    boundaries: ['不要默认展示凭证', '不要和生产登录页混淆', '不要被搜索索引'],
  },
  {
    slug: 'discord',
    route: '/discord',
    sourceFile: 'src/app/discord/page.tsx',
    title: 'Discord 入口切片',
    shortTitle: 'Discord',
    type: 'community',
    icon: UsersRound,
    summary: '社区入口页应说明加入目的、规则和外链安全。',
    primaryTask: '用户知道这个入口通向哪里、适合做什么、加入前要注意什么。',
    desktopStrategy: '主卡展示社区说明和加入按钮，侧栏列规则与替代反馈渠道。',
    mobileStrategy: '加入按钮前置，规则简短可折叠。',
    modules: ['社区说明', '加入按钮', '规则摘要', '替代反馈', '外链提示'],
    interactions: ['外链经 /go', '规则可展开', '加入失败有备用入口'],
    boundaries: ['不要直接裸跳外链', '不要把社区入口做成广告页', '不要缺少规则说明'],
  },
  {
    slug: 'demo-bestn-svg',
    route: '/demo/bestn-svg',
    sourceFile: 'src/app/demo/bestn-svg/page.tsx',
    title: 'Best N SVG Demo 切片',
    shortTitle: 'BestN Demo',
    type: 'generator',
    icon: Sparkles,
    summary: 'Demo 页面应明确这是实验入口，展示输入、预览和导出边界。',
    primaryTask: '用户能快速理解 SVG 生成效果，并回到正式工具。',
    desktopStrategy: '表单与预览并排，右侧展示实验说明和限制。',
    mobileStrategy: '预览在表单后展示，导出按钮保持可见。',
    modules: ['实验说明', '输入参数', 'SVG 预览', '导出动作', '返回正式入口'],
    interactions: ['参数变化更新预览', '导出失败给提示', '未登录时引导登录'],
    boundaries: ['不要混淆 demo 与正式功能', '不要隐藏实验限制', '不要使用过重装饰'],
  },
  {
    slug: 'demo-score-card',
    route: '/demo/score-card',
    sourceFile: 'src/app/demo/score-card/page.tsx',
    title: '成绩卡 Demo 切片',
    shortTitle: 'ScoreCard Demo',
    type: 'generator',
    icon: ImageIcon,
    summary: '成绩卡 Demo 用于验证视觉输出，应聚焦预览、主题和导出行为。',
    primaryTask: '用户能比较主题样式并理解最终导出效果。',
    desktopStrategy: '大预览为主，侧栏放主题、尺寸、导出设置。',
    mobileStrategy: '预览等比展示，设置项折叠在下方。',
    modules: ['成绩卡预览', '主题设置', '尺寸设置', '导出按钮', '实验说明'],
    interactions: ['主题切换不改变布局', '预览可放大', '导出状态清楚'],
    boundaries: ['不要把 Demo 做成入口首页', '不要堆过多参数', '不要牺牲预览区域'],
  },
];

export const sliceBySlug = new Map(lilithSlices.map((slice) => [slice.slug, slice]));

export function getSliceBySlug(slug: string) {
  return sliceBySlug.get(slug);
}

export function getSlicesByType(type: LilithSliceType) {
  return lilithSlices.filter((slice) => slice.type === type);
}
