#!/usr/bin/env node
// Generate embedded tips data from public/tips.txt into a TypeScript module.

import fs from 'fs';
import fsp from 'fs/promises';
import path from 'path';
import { createHash } from 'node:crypto';

function parseTips(text) {
  const lines = text
    .split(/\r?\n/g)
    .map((s) => s.trim())
    .filter((s) => s.length > 0 && !s.startsWith('#'));
  const set = new Set();
  const out = [];
  for (const l of lines) if (!set.has(l)) { set.add(l); out.push(l); }
  return out;
}

async function main() {
  const cwd = process.cwd();
  const tipsPath = path.join(cwd, 'public', 'tips.txt');
  if (!fs.existsSync(tipsPath)) {
    console.error('[precompile-tips] public/tips.txt not found');
    process.exit(1);
  }
  const raw = await fsp.readFile(tipsPath, 'utf8');
  const tips = parseTips(raw);
  if (tips.length === 0) {
    console.error('[precompile-tips] No valid tips parsed');
    process.exit(1);
  }
  const hash = createHash('sha256').update(tips.join('\n')).digest('hex').slice(0, 8);
  const outDir = path.join(cwd, 'src', 'app', 'components');
  await fsp.mkdir(outDir, { recursive: true });
  const outFile = path.join(outDir, 'tips.data.ts');
  const content = `/* auto-generated; DO NOT EDIT */\n// Generated by scripts/precompile-tips.mjs at ${new Date().toISOString()}\n// Source: public/tips.txt (sha256:${hash})\nexport const EMBEDDED_TIPS: string[] = ${JSON.stringify(tips, null, 2)};\n`;
  await fsp.writeFile(outFile, content, 'utf8');
  console.log('[precompile-tips] Wrote', path.relative(cwd, outFile), `(${tips.length} tips)`);
}

main().catch((err) => {
  console.error('[precompile-tips] Failed:', err);
  process.exit(1);
});

